"""Create customers and orders tables

Revision ID: 179b175ac6f0
Revises: 0e2dd5b6b933
Create Date: 2025-11-11 17:09:04.245804

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '179b175ac6f0'
down_revision: Union[str, None] = '0e2dd5b6b933'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
