"""Create customers and orders tables

Revision ID: 39df0cea68ea
Revises: daeff9cb6740
Create Date: 2025-11-11 16:41:03.244664

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '39df0cea68ea'
down_revision: Union[str, None] = 'daeff9cb6740'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
