"""add roles and permissions tables

Revision ID: 8a9fc786538e
Revises: b9de5889f1a5
Create Date: 2025-11-11 10:11:30.980308

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8a9fc786538e'
down_revision: Union[str, None] = 'b9de5889f1a5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('role_permissions',
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.Column('permission_id', sa.Integer(), nullable=False),
    sa.Column('granted_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['permission_id'], ['permissions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('role_id', 'permission_id')
    )
    op.create_table('user_roles',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.Column('assigned_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'role_id')
    )
    op.add_column('permissions', sa.Column('description', sa.String(length=255), nullable=True))
    op.drop_constraint('permissions_name_key', 'permissions', type_='unique')
    op.create_index(op.f('ix_permissions_name'), 'permissions', ['name'], unique=True)
    op.add_column('roles', sa.Column('is_active', sa.Boolean(), nullable=True))
    op.drop_constraint('roles_name_key', 'roles', type_='unique')
    op.create_index(op.f('ix_roles_name'), 'roles', ['name'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_roles_name'), table_name='roles')
    op.create_unique_constraint('roles_name_key', 'roles', ['name'])
    op.drop_column('roles', 'is_active')
    op.drop_index(op.f('ix_permissions_name'), table_name='permissions')
    op.create_unique_constraint('permissions_name_key', 'permissions', ['name'])
    op.drop_column('permissions', 'description')
    op.drop_table('user_roles')
    op.drop_table('role_permissions')
    # ### end Alembic commands ###
